name: Build PDFs

on: [push, pull_request]

jobs:
  build:
    name: Build all .pdf files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          set -vxeuo pipefail
          sudo apt-get update
          sudo apt-get install -y \
            texlive \
            texlive-latex-extra \
            texlive-fonts-extra \
            ghostscript

      - name: Run build
        run: |
          set -vxeuo pipefail
          ./build.sh

      - name: Check logs
        run: |
          cat tmp/RakitinMS_CV.log

      - name: Commit and push new files
        run: |
          git remote -v
          git branch -avv
          git status
          git config --global user.name "auto-push"
          git config --global user.email "mrakitin@users.noreply.github.com"
          export NOW=$(date +%Y%m%d%H%M%S)
          git checkout -b ${NOW}
          git add .
          git commit -m "Committing at ${NOW}"
          git log -n5
          git push -u origin ${NOW}
