name: Build PDFs

on: [push, pull_request]

jobs:
  build:
    name: Build all .pdf files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          set -vxeuo pipefail
          sudo apt-get update
          sudo apt-get install -y \
            texlive \
            texlive-latex-extra \
            texlive-fonts-extra \
            ghostscript

      - name: Run build
        run: |
          set -vxeuo pipefail
          ./build.sh

      - name: Check logs
        run: |
          cat tmp/RakitinMS_CV.log
