name: Build PDFs

on: [push, pull_request]

jobs:
  build:
    name: Build all .pdf files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      TZ: America/New_York

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          set -vxeuo pipefail
          sudo apt-get update
          sudo apt-get install -y \
            texlive \
            texlive-latex-extra \
            texlive-fonts-extra \
            ghostscript

      - name: Check time
        run: |
          set -vxeuo pipefail
          date
          echo "Time zone: ${TZ}"

      - name: Run build
        run: |
          set -vxeuo pipefail
          ./build.sh

      - name: Check logs
        run: |
          cat tmp/RakitinMS_CV.log

      - name: Commit new files
        run: |
          set -vxeuo pipefail

          export NOW="$(date +%Y%m%d%H%M%S)"
          export PUSH_BRANCH="${NOW}"
          # export PUSH_BRANCH="main"

          git config --global user.name "bot-auto-push"
          git config --global user.email "mrakitin@users.noreply.github.com"

          git remote -v
          git branch -avv
          git status

          if [ "${PUSH_BRANCH}" != "main" ]; then
              git checkout -b ${PUSH_BRANCH}
          fi

          git add *.pdf
          git commit -m "[BOT] Update on ${NOW}"
          git log -n5

      - name: Push new files
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          set -vxeuo pipefail

          echo "::group::env"
          env | sort -u
          echo "::endgroup::"

          git remote -v
          git branch -avv
          git status

          git log -n5
          git push -u origin ${PUSH_BRANCH}
