name: Check links

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linkchecker:
    name: Check links in the files are accessible
    # pull requests are a duplicate of a branch push if within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      TZ: America/New_York
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches
          # (https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches)
          fetch-depth: 0

      - uses: actions/setup-python@v4

      - name: Install linkchecker
        run: |
          set -vxeuo pipefail
          pip install -r requirements.txt

      - name: Run checks
        run: |
          set -vxeuo pipefail
          git --version
          # Uses https://linkchecker.github.io/linkchecker/.
          bash scripts/gen-links-html.sh

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: all-links
          path: all-links*.*
